# -*- coding: utf-8 -*-
"""PythonForDQE_hw_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-wQMAQ6pT5goMqWRVMviM-1r3jXxoH1
"""

import json

class JSONRecordImporter:
    def __init__(self, json_file='input.json', output_file='output.txt'):
        self.json_file = json_file
        self.output_file = output_file

    def process_json(self):
        if not os.path.exists(self.json_file):
            print(f"File {self.json_file} not found.")
            return

        with open(self.json_file, 'r') as f:
            records = json.load(f)

        for record in records:
            record_type = record.get("type")
            text = record.get("text")

            if record_type == "News":
                city = record.get("city", "Unknown")
                News(text, city).publish(self.output_file)
            elif record_type == "PrivateAd":
                expiration_date = record.get("expiration_date", "2099-12-31")
                PrivateAd(text, expiration_date).publish(self.output_file)
            elif record_type == "EventAnnouncement":
                event_date = record.get("event_date", "2099-12-31")
                location = record.get("location", "Unspecified")
                EventAnnouncement(text, event_date, location).publish(self.output_file)
            else:
                print(f"Unknown record type: {record_type}")

        os.remove(self.json_file)
        print(f"Processed and removed file: {self.json_file}")

json_importer = JSONRecordImporter()
json_importer.process_json()