# -*- coding: utf-8 -*-
"""str_hw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-wQMAQ6pT5goMqWRVMviM-1r3jXxoH1
"""

import re
string="""  tHis iz your homeWork, copy these Text to variable.


 You NEED TO normalize it fROM letter CASEs point oF View. also, create one MORE senTENCE witH LAST WoRDS of each existING SENtence and add it to the END OF this Paragraph.


 it iZ misspeLLing here. fix“iZ” with correct “is”, but ONLY when it Iz a mistAKE.


 last iz TO calculate nuMber OF Whitespace characteRS in this Tex. caREFULL, not only Spaces, but ALL whitespaces. I got 87."""


string = string.lower().replace('iz','is')
sentences = re.split(r'(?<=[.!?])\s+', string.strip())
normalized_sentences = [s.capitalize() for s in sentences]


last_words = [s.strip().split()[-1].strip('.,') for s in normalized_sentences if len(s.strip()) > 0]
new_sentence = ' '.join(last_words) + '.'
normalized_sentences.append(new_sentence)

whitespace_count = sum(1 for c in string if c.isspace())

final_text = '\n'.join(normalized_sentences)
print("Normalized and expanded text:\n")
print(final_text)
print(f"\nTotal whitespace characters: {whitespace_count}")